name: ARM Linux Build for Emuelec4.7 (Fixed Unicorn)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mrp:
    name: Build MRP Emulator (aarch64)
    runs-on: ubuntu-22.04
    env:
      TOOLCHAIN: aarch64-linux-gnu
      ARCH: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure architecture
        run: |
          sudo dpkg --add-architecture ${{ env.ARCH }}

      - name: Configure APT sources
        run: |
          sudo rm -f /etc/apt/sources.list.d/*.list
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse" | sudo tee /etc/apt/sources.list
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{ env.ARCH }}] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/${{ env.ARCH }}.list
          echo "deb [arch=${{ env.ARCH }}] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/${{ env.ARCH }}.list

      - name: Install dependencies (including GLib)
        run: |
          sudo apt-get update -y --fix-missing || true
          # 安装GLib（解决g_*函数缺失）和其他必要依赖
          sudo apt-get install -y \
            gcc-${{ env.TOOLCHAIN }} \
            g++-${{ env.TOOLCHAIN }} \
            libsdl2-dev:${{ env.ARCH }} \
            zlib1g-dev:${{ env.ARCH }} \
            libglib2.0-dev:${{ env.ARCH }} \  # 关键：添加GLib开发库
            make \
            wget \
            unzip \
            pkg-config \
            qemu-user-static \
            git \
            cmake

      - name: Build Unicorn Engine (ARM-only)
        run: |
          git clone https://github.com/unicorn-engine/unicorn.git
          cd unicorn
          # 使用较新的稳定版本（1.0.3修复了部分交叉编译问题）
          git checkout 1.0.3
          
          # 配置仅支持ARM架构，禁用其他架构和示例程序
          ./configure \
            --prefix=/usr/${{ env.TOOLCHAIN }} \
            --cross-prefix=${{ env.TOOLCHAIN }}- \
            --enable-static \
            --disable-shared \
            --enable-arm \  # 仅启用ARM架构
            --disable-x86 \
            --disable-mips \
            --disable-sparc \
            --disable-m68k \
            --disable-sample \  # 禁用示例程序（避免x86依赖）
            --extra-cflags="-I/usr/${{ env.TOOLCHAIN }}/include" \
            --extra-ldflags="-L/usr/${{ env.TOOLCHAIN }}/lib"
          
          # 编译并安装
          make -j$(nproc)
          sudo make install
          cd ..
          sudo ldconfig

      - name: Build Capstone
        run: |
          wget https://github.com/capstone-engine/capstone/archive/4.0.2.tar.gz -O capstone.tar.gz
          tar -zxf capstone.tar.gz
          cd capstone-4.0.2
          ./make.sh cross-${{ env.ARCH }}
          sudo make install PREFIX=/usr/${{ env.TOOLCHAIN }}
          cd ..

      - name: Build MRP emulator
        run: |
          export CC=${{ env.TOOLCHAIN }}-gcc
          export CFLAGS="-I/usr/${{ env.TOOLCHAIN }}/include -march=armv8-a -O2"
          export LDFLAGS="-L/usr/${{ env.TOOLCHAIN }}/lib -lunicorn -lglib-2.0"  # 链接GLib
          
          cd mythroad && make full && cd ..
          make VMRP=1 DEBUG=0
          file ./bin/vmrp

      - name: Package for Emuelec
        run: |
          mkdir -p vmrp-portmaster/${{ env.ARCH }}
          cp ./bin/vmrp vmrp-portmaster/${{ env.ARCH }}/
          for lib in $(qemu-${{ env.ARCH }}-static ./bin/vmrp --version 2>&1 | grep -oP 'lib\S+'); do
            cp /usr/${{ env.TOOLCHAIN }}/lib/$lib* vmrp-portmaster/${{ env.ARCH }}/
          done
          echo '{"name":"vmrp","version":"1.0","architecture":"${{ env.ARCH }}","executable":"${{ env.ARCH }}/vmrp"}' > vmrp-portmaster/portmaster.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vmrp-emuelec-${{ env.ARCH }}
          path: vmrp-portmaster/
