name: ARM Linux Build for Emuelec4.7 (Ruffle-style Fixed)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mrp:
    name: Build MRP Emulator (aarch64)
    runs-on: ubuntu-22.04
    env:
      TOOLCHAIN: aarch64-linux-gnu
      ARCH: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure architecture
        run: |
          sudo dpkg --add-architecture ${{ env.ARCH }}

      - name: Configure APT sources (Ruffle-style)
        run: |
          # 完全参考 Ruffle 的源配置逻辑：分离主机与目标架构源
          sudo rm -f /etc/apt/sources.list.d/*.list
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse" | sudo tee /etc/apt/sources.list
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{ env.ARCH }}] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/${{ env.ARCH }}.list
          echo "deb [arch=${{ env.ARCH }}] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/${{ env.ARCH }}.list

      - name: Update packages
        run: |
          # Ruffle 处理源更新的方式：忽略非致命错误
          sudo apt-get update -y --fix-missing || true

      - name: Install dependencies (Ruffle-style)
        run: |
          # 移除行内注释，保持命令纯净（Ruffle 依赖安装无多余注释）
          sudo apt-get install -y \
            gcc-${{ env.TOOLCHAIN }} \
            g++-${{ env.TOOLCHAIN }} \
            libsdl2-dev:${{ env.ARCH }} \
            zlib1g-dev:${{ env.ARCH }} \
            make \
            wget \
            unzip \
            pkg-config \
            qemu-user-static \
            git \
            cmake

      - name: Build Unicorn from source
        run: |
          git clone https://github.com/unicorn-engine/unicorn.git
          cd unicorn
          git checkout 1.0.2
          mkdir build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER=${{ env.TOOLCHAIN }}-gcc \
            -DCMAKE_CXX_COMPILER=${{ env.TOOLCHAIN }}-g++ \
            -DCMAKE_INSTALL_PREFIX=/usr/${{ env.TOOLCHAIN }} \
            -DBUILD_SHARED_LIBS=ON
          make -j$(nproc)
          sudo make install
          cd ../..
          sudo ldconfig

      - name: Build Capstone
        run: |
          wget https://github.com/capstone-engine/capstone/archive/4.0.2.tar.gz -O capstone.tar.gz
          tar -zxf capstone.tar.gz
          cd capstone-4.0.2
          ./make.sh cross-${{ env.ARCH }}
          sudo make install PREFIX=/usr/${{ env.TOOLCHAIN }}
          cd ..

      - name: Build MRP emulator
        run: |
          export CC=${{ env.TOOLCHAIN }}-gcc
          export CFLAGS="-I/usr/${{ env.TOOLCHAIN }}/include -march=armv8-a -O2"
          export LDFLAGS="-L/usr/${{ env.TOOLCHAIN }}/lib"
          
          cd mythroad && make full && cd ..
          make VMRP=1 DEBUG=0
          file ./bin/vmrp

      - name: Package for Emuelec
        run: |
          mkdir -p vmrp-portmaster/${{ env.ARCH }}
          cp ./bin/vmrp vmrp-portmaster/${{ env.ARCH }}/
          # 收集依赖（参考 Ruffle 打包逻辑）
          for lib in $(qemu-${{ env.ARCH }}-static ./bin/vmrp --version 2>&1 | grep -oP 'lib\S+'); do
            cp /usr/${{ env.TOOLCHAIN }}/lib/$lib* vmrp-portmaster/${{ env.ARCH }}/
          done
          echo '{"name":"vmrp","version":"1.0","architecture":"${{ env.ARCH }}","executable":"${{ env.ARCH }}/vmrp"}' > vmrp-portmaster/portmaster.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vmrp-emuelec-${{ env.ARCH }}
          path: vmrp-portmaster/
