name: ARM Linux Build for Emuelec4.7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [aarch64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libsdl2-dev:arm64 \
            zlib1g-dev:arm64 \
            make cmake \
            wget unzip

      - name: Build Unicorn from source
        run: |
          wget https://github.com/unicorn-engine/unicorn/archive/refs/tags/1.0.2.zip
          unzip 1.0.2.zip
          cd unicorn-1.0.2
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
                   -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
                   -DCMAKE_INSTALL_PREFIX=/usr/aarch64-linux-gnu
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Build MythRoad
        run: |
          cd mythroad
          make CC=aarch64-linux-gnu-gcc \
               AR=aarch64-linux-gnu-ar \
               CFLAGS="-DVMRP -I/usr/aarch64-linux-gnu/include" \
               LDFLAGS="-L/usr/aarch64-linux-gnu/lib" \
               full

      - name: Build main VMRP
        run: |
          cd vmrp  # 关键修复：进入正确目录
          make CC=aarch64-linux-gnu-gcc \
               CFLAGS="-DVMRP -I/usr/aarch64-linux-gnu/include" \
               LDFLAGS="-L/usr/aarch64-linux-gnu/lib -lSDL2 -lunicorn -lz -lm" \
               DEBUG=0

      - name: Prepare output
        run: |
          mkdir -p vmrp-arm64
          cp vmrp/bin/vmrp vmrp-arm64/  # 修复输出路径
          
          # 复制依赖库（使用实际路径）
          cp /usr/aarch64-linux-gnu/lib/libunicorn.so.1 vmrp-arm64/
          cp /usr/aarch64-linux-gnu/lib/libz.so.1 vmrp-arm64/
          cp /usr/aarch64-linux-gnu/lib/libSDL2-2.0.so.0 vmrp-arm64/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vmrp-emuelec-s905l3a
          path: vmrp-arm64
