name: ARM Linux Build for Emuelec4.7

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [aarch64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: StarCatL/vmrp
          submodules: true

      - name: Set up QEMU for ARM64
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo update-binfmts --enable qemu-aarch64
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up cross-compilation environment
        run: |
          # 添加ARM64架构支持
          sudo dpkg --add-architecture arm64
          
          # 配置APT源
          sudo tee /etc/apt/sources.list.d/arm64.list <<EOF
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse
          EOF
          
          # 更新软件包列表
          sudo apt-get update
          
          # 安装ARM64依赖
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libsdl2-dev:arm64 \
            zlib1g-dev:arm64 \
            make \
            wget \
            unzip

      - name: Install unicorn and capstone
        run: |
          # 使用正确的ARM64预编译包
          wget https://github.com/unicorn-engine/unicorn/releases/download/2.0.1/unicorn-2.0.1-linux-aarch64.tar.gz
          tar -zxf unicorn-2.0.1-linux-aarch64.tar.gz
          sudo cp -r unicorn-2.0.1-linux-aarch64/include/* /usr/aarch64-linux-gnu/include/
          sudo cp -r unicorn-2.0.1-linux-aarch64/lib/* /usr/aarch64-linux-gnu/lib/
          
          wget https://github.com/capstone-engine/capstone/releases/download/5.0.1/capstone-5.0.1-aarch64.tar.gz
          tar -zxf capstone-5.0.1-aarch64.tar.gz
          sudo cp -r capstone-5.0.1-aarch64/include/* /usr/aarch64-linux-gnu/include/
          sudo cp -r capstone-5.0.1-aarch64/lib/* /usr/aarch64-linux-gnu/lib/

      - name: Build mythroad module
        run: |
          cd mythroad
          make CC=aarch64-linux-gnu-gcc \
               AR=aarch64-linux-gnu-ar \
               CFLAGS="-I/usr/aarch64-linux-gnu/include" \
               LDFLAGS="-L/usr/aarch64-linux-gnu/lib" \
               full

      - name: Build main vmrp
        run: |
          make CC=aarch64-linux-gnu-gcc \
               CFLAGS="-DVMRP -I/usr/aarch64-linux-gnu/include" \
               LDFLAGS="-L/usr/aarch64-linux-gnu/lib -lSDL2 -lunicorn -lz -lm" \
               DEBUG=0

      - name: Prepare output
        run: |
          mkdir -p vmrp-arm64
          cp ./bin/vmrp ./vmrp-arm64/
          aarch64-linux-gnu-strip ./vmrp-arm64/vmrp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vmrp-emuelec-s905l3a
          path: vmrp-arm64/
